apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: splitbot
resources:
  - ../../base
  - splitbot-sealed.yaml
  - tunnel-sealed.yaml
images:
  - name: ghcr.io/erix/splitbot
    newTag: main-12-sha-3dc2b8b74f5adc35337543f6b646bda130999dad # {"$imagepolicy":"flux-system:splitbot:tag"}
