apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: splitbot-tunnel-secret
  namespace: splitbot
spec:
  encryptedData:
    TUNNEL_TOKEN: AgDJEgd90gBDQHHN6gtoIhEx1YYjiDEe0qq/7QzH4qMqgt9MtcQ2V7vnZEwZnK7QlhG4MdGLEX72htRf6LmmKyj7nkVMyWm7EkBiWsirOckTEQaA3uJv1++iUfdQVeza+BKs7SOJvK57K5aXHJs4GQEECphpEUovDjMGa/nmhWzWieK6mk9wezAsVsOL/NI//O337Si7RRe3gXQpVh3k91whH00cphpsfGFAgKtGbyrCbHJJcaQByn6nfmargMCvhDiMjIcOCr7GiIJ2WzKLxX/Y3vO7OgUG5vk8te2PzuYBRGaniI8qG0bRnDvjjMOf7y6vLuJOYs6yxzR62Ls6cBZxwlmD4UFMcn+Vmmu2f//oIZdVil0EEpc8xpgOr0sDwUySti7knJu76u3+EVsgo9e+Brn59z8fLN6UdeVhPEZ+cHvPcrcvF2UmimpXf+mqUXIPLaQgVGuzwkZD+ck6awGpqFayahJRgecl0bCMequm57LsS0JacmBpU2+zYmorqZDIoTKWthyDxenHozt+VSKIPa5YqVWgF5k8OaWoOYkN+lVaKALaroUJzYTASGn0WuKHywYaIeZuCxmbI66pxWvS1/aKzRy37dTDqM07VJXlx1L398Q2o6E08NLrRF9zdGnUG8zHHMPanYm6Tou6swAZyA5U41JUhC1m9mCnDvSr0BYBgLVzN20y3IjE3j/NxDYjkMmIRPqSh3Wocdc8J4AzqUtRn3gvP9mitQECqig5eITFFAhpEWO/YqEjsvZ/jv4nnpKjoz2xDa6Sp2CpGFsenMJcVdhkd6bdbjl0h8tjw9N51emcf4vUE7C67J+jvgjhBEy+xOFpIz7OOqrDxETza5BIYNrmwmu8SAX6OCrQS38GqaXoVbitMqptifPY0ANQrnwsA703YhboDvb/ax1uOdTRlWtCGOdDtRtt0PeFumauY1A=
  template:
    metadata:
      creationTimestamp: null
      name: splitbot-tunnel-secret
      namespace: splitbot
