apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared-tunnel-secret
  namespace: tunnel
spec:
  encryptedData:
    TUNNEL_TOKEN: AgBzyE8zRoc72QE1TPiXC4ccLR/e9kl4FX9YF851mmTlFvC1rQKwcFs7py4KLpg14Co09EVBLiXZZW99Sp3WIelCVlyupbA1whWHnVYU3/EiLLPWKkSHYat4V/xpMBQhOScX41pcscQhQJKkEIy713srUDGza3ImhHxDsbiwKourQp+SG9cQvnmvEtG/CjTiaK3jdqcYbV+3j1RYZHVdBptpvbFIh+qgRkWz65HRJuYtnU65FEPGwXtaUF3gl6PCWo0Nv70iQ2di1RYcUw5pVaipjh9MUMGZIarQ/7sb2FvrRSoINanSJNQ+pku+HYFISgAp72SfahihGS88dTF2o/12v8RFtGM+3IAVPfnbkaPA0xZRwgNALl0IFbVI5tfBpSmDMt1FmRQRbleVAoMN5OH4I6NOOOFUB0eZexrpxH3abWZAvlC21yG4kYsOoI9YhfvOdWTr+OcIOhqAsZwMl5lAI9vdzyQUSmNYK6ZXfA13XT2OULZUWIyajMWyrYJ3Q7CHwxnlkeY3sYcKLBqUW49sXIvxb7j7vM3Eqtut7UwZ4gLYb64zgd3Yin/RzcwaQJb36OK81t6b+naLMaslOZvoZ2pW4kIBFYgRNL5peVAXJGYfSH3kyYf372h/JPtpgsLinpV2gGULIKwnRwbbDPEKN1u6tzmWH7zi7/dcHbIYpWH72+VreTgD8/x69jXAI0fhLREeqVVRdNjMB7g7/ImbnsRuOcIlRVb4mjhRfWP1aTcY0r77XGXLjA6NvC3nq+f1yr/DkBsFzib5Dv9QQfdzwfZmANqNuElWRHEC8WId6xicirJ2mXmgnNEOmT66RmG0qw3WINpyUJf1xRmeSSm4LlGzhWMnk7OHYMTl0UNXZGAuq098KDhcvb8McnbHtl4TdzH7V2uLHC1NMJ7AFS9vnnELLX5aBcNjQRh95bnv6PFr9u0=
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared-tunnel-secret
      namespace: tunnel
