apiVersion: v1
kind: Service
metadata:
  name: splitbot
  namespace: splitbot
  labels:
    app.kubernetes.io/name: splitbot
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: splitbot
  ports:
    - name: http
      port: 3000
      targetPort: 3000
